
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwkzatbaxdvedrwfyyof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3a3phdGJheGR2ZWRyd2Z5eW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNDIzMzEsImV4cCI6MjA1OTcxODMzMX0.5IHPciyaEVstcqcmAHZQUa9zXCzJeo36JERrXeEUpaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
  }
});

// Helper para lidar com erros de RLS
export const handleSupabaseError = (error: any): string => {
  console.error("Erro Supabase detalhado:", error);
  
  if (error?.code === '42501') {
    return 'Erro de permissão: você não tem autorização para realizar esta ação.';
  } else if (error?.message?.includes('violates row-level security policy')) {
    return 'Erro de permissão: você não tem autorização para realizar esta ação devido às políticas de segurança.';
  } else {
    return `Erro ao processar solicitação: ${error?.message || 'Desconhecido'}`;
  }
};
